- name: Check monitoring containers are running
  command: docker ps --filter status=running
  register: result
  changed_when: false

- name: Show running containers
  debug:
    msg: "{{ result.stdout_lines }}"