project_base_dir: /home/tst/devops-lab

services:
  portainer:
    dir: "{{ project_base_dir }}/portainer"
  monitoring:
    dir: "{{ project_base_dir }}/monitoring"

# Grafana admin password (переменная окружения GRAFANA_PASSWORD)
grafana_admin_password: "{{ lookup('env', 'GRAFANA_PASSWORD') | default('devops123', true) }}"
prometheus_port: 9091