- name: Check portainer is running
  command: docker ps --filter name=portainer --filter status=running
  register: result
  changed_when: false

- name: Show portainer status
  debug:
    msg: "{{ result.stdout_lines }}"