apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: llm-api
  namespace: default
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    traefik.ingress.kubernetes.io/router.middlewares: default-llm-whitelist@kubernetescrd
spec:
  ingressClassName: traefik
  tls:
  - hosts:
    - llm.ai-devops.pp.ua
    secretName: llm-api-tls
  rules:
  - host: llm.ai-devops.pp.ua
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: llm-api
            port:
              number: 80
