apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: node-exporter
  namespace: observability
spec:
  selector:
    matchLabels:
      app: node-exporter
  template:
    metadata:
      labels:
        app: node-exporter
    spec:
      hostNetwork: true
      containers:
      - name: node-exporter
        image: prom/node-exporter:v1.8.2
        args:
          - --path.rootfs=/host
        resources:
          limits:
            memory: 64Mi
            cpu: 50m
          requests:
            memory: 32Mi
            cpu: 25m
        volumeMounts:
          - name: root
            mountPath: /host
            readOnly: true
      volumes:
        - name: root
          hostPath:
            path: /
